[default]
forum = true
# Pathes
db_path = 'data/db'
log_path = 'logs/bot.log'
# General
timezone = 'US/Eastern'
# Internal parameters
date_format = '%Y-%m-%d'
datetime_format = '%Y-%m-%d %H:%M:%S'
conversation_timeout = 60   # in seconds

[prod]
debug = false
bot_username = '@PLACEHOLDER'
admins = ['@PLACEHOLDER']

token = 'SECRET_PLACEHOLDER'

[dev]
debug = true
bot_username = '@PLACEHOLDER'
admins = ['@PLACEHOLDER']

token = 'SECRET_PLACEHOLDER'
